--
-- JBoss, Home of Professional Open Source
-- Copyright 2013, Red Hat, Inc. and/or its affiliates, and individual
-- contributors by the @authors tag. See the copyright.txt in the
-- distribution for a full listing of individual contributors.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- http://www.apache.org/licenses/LICENSE-2.0
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- You can use this file to load seed data into the database using SQL statements
USE rest_services_db;
INSERT INTO `rest_services_db`.`user` (`id`, `first_name`, `last_name`, `password`, `registration_status`, `token`, `username`) VALUES ('1', 'Xavier', 'Ramirez', '', 'CONFIRMED', '', 'xaviercobain88');
INSERT INTO `rest_services_db`.`license_plan` (`id`, `description`, `price`, `status`, `total_companies`, `total_users`) VALUES ('1', 'Plan Básico', '47', 'ACTIVE', '5', '1');
INSERT INTO `rest_services_db`.`license` (`id`, `used_companies`, `used_users`, `license_plan_id`) VALUES ('1', '0', '0', '1');
INSERT INTO `rest_services_db`.`license_user` (`id`, `license_id`, `user_id`) VALUES ('1', '1', '1');
INSERT INTO `company` VALUES (1,NULL,'1718263153','Esta es una razon social',1);
INSERT INTO `assigment` VALUES (1,1);

-- Accounts
INSERT INTO `rest_services_db`.`account` (`id`, `account_type`, `account_value_type`, `description`, `name`, `order_weight`) VALUES ('1', 'ASSETS', 'POSITIVE', 'ACTIVO', 'ACTIVO', '10');
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','101', 'DUAL', 'ACTIVO CORRIENTE', 'ACTIVO CORRIENTE', '20', '1'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10101', 'POSITIVE', 'EFECTIVO Y EQUIVALENTES AL EFECTIVO', 'EFECTIVO Y EQUIVALENTES AL EFECTIVO', '30', '101'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10102', 'DUAL', 'ACTIVOS FINANCIEROS', 'ACTIVOS FINANCIEROS', '40', '101'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010201', 'POSITIVE', 'ACTIVOS FINANCIEROS A VALOR RAZONABLE CON CAMBIOS EN RESULTADOS', 'ACTIVOS FINANCIEROS A VALOR RAZONABLE CON CAMBIOS EN RESULTADOS', '50', '10102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010202', 'POSITIVE', 'ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA', 'ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA', '60', '10102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010203', 'POSITIVE', 'ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO', 'ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO', '70', '10102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010204', 'POSITIVE', '(-) PROVISION POR DETERIORO', '(-) PROVISION POR DETERIORO', '80', '10102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010205', 'NEGATIVE', 'DOCUMENTOS Y CUENTAS POR COBRAR CLIENTES NO RELACIONADOS', 'DOCUMENTOS Y CUENTAS POR COBRAR CLIENTES NO RELACIONADOS', '90', '10102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','101020501', 'POSITIVE', 'DE ACTIVIDADES ORDINARIAS QUE GENEREN INTERESES', 'DE ACTIVIDADES ORDINARIAS QUE GENEREN INTERESES', '100', '1010205'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','101020502', 'POSITIVE', 'DE ACTIVIDADES ORDINARIAS QUE NO GENEREN INTERESES', 'DE ACTIVIDADES ORDINARIAS QUE NO GENEREN INTERESES', '110', '1010205'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010206', 'POSITIVE', 'DOCUMENTOS Y CUENTAS POR COBRAR CLIENTES RELACIONADOS', 'DOCUMENTOS Y CUENTAS POR COBRAR CLIENTES RELACIONADOS', '120', '10102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010207', 'POSITIVE', 'OTRAS CUENTAS POR COBRAR RELACIONADAS', 'OTRAS CUENTAS POR COBRAR RELACIONADAS', '130', '10102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010208', 'POSITIVE', 'OTRAS CUENTAS POR COBRAR', 'OTRAS CUENTAS POR COBRAR', '140', '10102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010209', 'NEGATIVE', '(-) PROVISIÓN CUENTAS INCOBRABLES Y DETERIORO', '(-) PROVISIÓN CUENTAS INCOBRABLES Y DETERIORO', '150', '10102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10103', 'DUAL', 'INVENTARIOS', 'INVENTARIOS', '160', '101'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010301', 'POSITIVE', 'INVENTARIOS DE MATERIA PRIMA', 'INVENTARIOS DE MATERIA PRIMA', '170', '10103'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010302', 'POSITIVE', 'INVENTARIOS DE PRODUCTOS EN PROCESO', 'INVENTARIOS DE PRODUCTOS EN PROCESO', '180', '10103'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010303', 'POSITIVE', 'INVENTARIOS DE SUMINISTROS O MATERIALES A SER CONSUMIDOS EN EL PROCESO DE PRODUCCION', 'INVENTARIOS DE SUMINISTROS O MATERIALES A SER CONSUMIDOS EN EL PROCESO DE PRODUCCION', '190', '10103'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010304', 'POSITIVE', 'INVENTARIOS DE SUMINISTROS O MATERIALES A SER CONSUMIDOS EN EL LA PRESTACION DEL SERVICIO', 'INVENTARIOS DE SUMINISTROS O MATERIALES A SER CONSUMIDOS EN EL LA PRESTACION DEL SERVICIO', '200', '10103'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010305', 'POSITIVE', 'INVENTARIOS DE PROD. TERM. Y MERCAD. EN ALMACÉN - PRODUCIDO POR LA COMPAÑÍA', 'INVENTARIOS DE PROD. TERM. Y MERCAD. EN ALMACÉN - PRODUCIDO POR LA COMPAÑÍA', '210', '10103'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010306', 'POSITIVE', 'INVENTARIOS DE PROD. TERM. Y MERCAD. EN ALMACÉN - COMPRADO A DE TERCEROS', 'INVENTARIOS DE PROD. TERM. Y MERCAD. EN ALMACÉN - COMPRADO A DE TERCEROS', '220', '10103'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010307', 'POSITIVE', 'MERCADERÍAS EN TRÁNSITO', 'MERCADERÍAS EN TRÁNSITO', '230', '10103'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010308', 'POSITIVE', 'OBRAS EN CONSTRUCCION', 'OBRAS EN CONSTRUCCION', '240', '10103'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010309', 'POSITIVE', 'OBRAS TERMINADAS', 'OBRAS TERMINADAS', '250', '10103'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010310', 'POSITIVE', 'MATERIALES O BIENES PARA LA CONSTRUCCION', 'MATERIALES O BIENES PARA LA CONSTRUCCION', '260', '10103'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010311', 'POSITIVE', 'INVENTARIOS REPUESTOS, HERRAMIENTAS Y ACCESORIOS', 'INVENTARIOS REPUESTOS, HERRAMIENTAS Y ACCESORIOS', '270', '10103'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010312', 'POSITIVE', 'OTROS INVENTARIOS', 'OTROS INVENTARIOS', '280', '10103'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010313', 'NEGATIVE', '(-) PROVISIÓN POR VALOR NETO DE REALIZACIÓN Y OTRAS PERDIDAS EN INVENTARIO', '(-) PROVISIÓN POR VALOR NETO DE REALIZACIÓN Y OTRAS PERDIDAS EN INVENTARIO', '290', '10103'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10104', 'DUAL', 'SERVICIOS Y OTROS PAGOS ANTICIPADOS', 'SERVICIOS Y OTROS PAGOS ANTICIPADOS', '300', '101'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010401', 'DUAL', 'SEGUROS PAGADOS POR ANTICIPADO', 'SEGUROS PAGADOS POR ANTICIPADO', '310', '10104'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010402', 'POSITIVE', 'ARRIENDOS PAGADOS POR ANTICIPADO', 'ARRIENDOS PAGADOS POR ANTICIPADO', '320', '10104'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010403', 'POSITIVE', 'ANTICIPOS A PROVEEDORES', 'ANTICIPOS A PROVEEDORES', '330', '10104'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010404', 'POSITIVE', 'OTROS ANTICIPOS ENTREGADOS', 'OTROS ANTICIPOS ENTREGADOS', '340', '10104'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10105', 'DUAL', 'ACTIVOS POR IMPUESTOS CORRIENTES', 'ACTIVOS POR IMPUESTOS CORRIENTES', '350', '101'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010501', 'POSITIVE', 'CRÉDITO TRIBUTARIO A FAVOR DE LA EMPRESA (IVA)', 'CRÉDITO TRIBUTARIO A FAVOR DE LA EMPRESA (IVA)', '360', '10105'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010502', 'POSITIVE', 'CRÉDITO TRIBUTARIO A FAVOR DE LA EMPRESA ( I. R.)', 'CRÉDITO TRIBUTARIO A FAVOR DE LA EMPRESA ( I. R.)', '370', '10105'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1010503', 'POSITIVE', 'ANTICIPO DE IMPUESTO A LA RENTA', 'ANTICIPO DE IMPUESTO A LA RENTA', '380', '10105'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10106', 'POSITIVE', 'ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA Y OPERACIONES DISCONTINUADAS', 'ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA Y OPERACIONES DISCONTINUADAS', '390', '101'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10107', 'POSITIVE', 'CONSTRUCCIONES EN PROCESO (NIC 11 Y SECC.23 PYMES)', 'CONSTRUCCIONES EN PROCESO (NIC 11 Y SECC.23 PYMES)', '400', '101'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10108', 'POSITIVE', 'OTROS ACTIVOS CORRIENTES', 'OTROS ACTIVOS CORRIENTES', '410', '101'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','102', 'DUAL', 'ACTIVO NO CORRIENTE', 'ACTIVO NO CORRIENTE', '430', '1'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10201', 'DUAL', 'PROPIEDADES, PLANTA Y EQUIPO', 'PROPIEDADES, PLANTA Y EQUIPO', '450', '102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020101', 'POSITIVE', 'TERRENOS', 'TERRENOS', '460', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020102', 'POSITIVE', 'EDIFICIOS', 'EDIFICIOS', '470', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020103', 'POSITIVE', 'CONTRUCCIONES EN CURSO', 'CONTRUCCIONES EN CURSO', '480', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020104', 'POSITIVE', 'INSTALACIONES', 'INSTALACIONES', '490', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020105', 'POSITIVE', 'MUEBLES Y ENSERES', 'MUEBLES Y ENSERES', '500', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020106', 'POSITIVE', 'MAQUINARIA Y EQUIPO', 'MAQUINARIA Y EQUIPO', '510', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020107', 'POSITIVE', 'NAVES, AERONAVES, BARCAZAS Y SIMILARES', 'NAVES, AERONAVES, BARCAZAS Y SIMILARES', '520', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020108', 'POSITIVE', 'EQUIPO DE COMPUTACIÓN', 'EQUIPO DE COMPUTACIÓN', '530', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020109', 'POSITIVE', 'VEHÍCULOS, EQUIPOS DE TRANSPORTE Y EQUIPO CAMINERO MÓVIL', 'VEHÍCULOS, EQUIPOS DE TRANSPORTE Y EQUIPO CAMINERO MÓVIL', '540', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020110', 'POSITIVE', 'OTROS PROPIEDADES, PLANTA Y EQUIPO', 'OTROS PROPIEDADES, PLANTA Y EQUIPO', '550', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020111', 'POSITIVE', 'REPUESTOS Y HERRAMIENTAS', 'REPUESTOS Y HERRAMIENTAS', '560', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020112', 'NEGATIVE', '(-) DEPRECIACIÓN ACUMULADA PROPIEDADES, PLANTA Y EQUIPO', '(-) DEPRECIACIÓN ACUMULADA PROPIEDADES, PLANTA Y EQUIPO', '570', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020113', 'NEGATIVE', '(-) DETERIORO ACUMULADO DE PROPIEDADES, PLANTA Y EQUIPO', '(-) DETERIORO ACUMULADO DE PROPIEDADES, PLANTA Y EQUIPO', '580', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020114', 'DUAL', 'ACTIVOS DE EXPLORACION Y EXPLOTACION', 'ACTIVOS DE EXPLORACION Y EXPLOTACION', '590', '10201'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','102011401', 'POSITIVE', 'ACTIVOS DE EXPLORACION Y EXPLOTACION', 'ACTIVOS DE EXPLORACION Y EXPLOTACION', '600', '1020114'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','102011402', 'NEGATIVE', '(-) AMORTIZACION ACUMULADA DE ACTIVOS DE EXPLORACIÓN Y EXPLOTACIÓN', '(-) AMORTIZACION ACUMULADA DE ACTIVOS DE EXPLORACIÓN Y EXPLOTACIÓN', '610', '1020114'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','102011403', 'NEGATIVE', '(-) DETERIORO ACUMULADO DE ACTIVOS DE EXPLORACIÓN Y EXPLOTACIÓN', '(-) DETERIORO ACUMULADO DE ACTIVOS DE EXPLORACIÓN Y EXPLOTACIÓN', '620', '1020114'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10202', 'DUAL', 'PROPIEDADES DE INVERSIÓN', 'PROPIEDADES DE INVERSIÓN', '640', '102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020201', 'POSITIVE', 'TERRENOS', 'TERRENOS', '650', '10202'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020202', 'POSITIVE', 'EDIFICIOS', 'EDIFICIOS', '660', '10202'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020203', 'NEGATIVE', '(-) DEPRECIACION ACUMULADA DE PROPIEDADES DE INVERSIÓN', '(-) DEPRECIACION ACUMULADA DE PROPIEDADES DE INVERSIÓN', '670', '10202'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020204', 'NEGATIVE', '(-) DETERIORO ACUMULADO DE PROPIEDADES DE INVERSIÓN', '(-) DETERIORO ACUMULADO DE PROPIEDADES DE INVERSIÓN', '680', '10202'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10203', 'DUAL', 'ACTIVOS BIOLOGICOS', 'ACTIVOS BIOLOGICOS', '700', '102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020301', 'POSITIVE', 'ANIMALES VIVOS EN CRECIMIENTO', 'ANIMALES VIVOS EN CRECIMIENTO', '710', '10203'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020302', 'POSITIVE', 'ANIMALES VIVOS EN PRODUCCION', 'ANIMALES VIVOS EN PRODUCCION', '720', '10203'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020303', 'POSITIVE', 'PLANTAS EN CRECIMIENTO', 'PLANTAS EN CRECIMIENTO', '730', '10203'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020304', 'POSITIVE', 'PLANTAS EN PRODUCCION', 'PLANTAS EN PRODUCCION', '740', '10203'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020305', 'NEGATIVE', '(-) DEPRECIACION ACUMULADA DE ACTIVOS BIOLÓGICOS', '(-) DEPRECIACION ACUMULADA DE ACTIVOS BIOLÓGICOS', '750', '10203'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020306', 'NEGATIVE', '(-) DETERIORO ACUMULADO DE ACTIVOS BIOLOGÍCOS', '(-) DETERIORO ACUMULADO DE ACTIVOS BIOLOGÍCOS', '760', '10203'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10204', 'DUAL', 'ACTIVO INTANGIBLE', 'ACTIVO INTANGIBLE', '780', '102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020401', 'POSITIVE', 'PLUSVALÍAS', 'PLUSVALÍAS', '790', '10204'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020402', 'POSITIVE', 'MARCAS, PATENTES, DERECHOS DE LLAVE , CUOTAS PATRIMONIALES Y OTROS SIMILARES', 'MARCAS, PATENTES, DERECHOS DE LLAVE , CUOTAS PATRIMONIALES Y OTROS SIMILARES', '800', '10204'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020403', 'POSITIVE', 'ACTIVOS DE EXPLORACION Y EXPLOTACION', 'ACTIVOS DE EXPLORACION Y EXPLOTACION', '810', '10204'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020404', 'NEGATIVE', '(-) DETERIORO ACUMULADO DE ACTIVO INTANGIBLE', '(-) DETERIORO ACUMULADO DE ACTIVO INTANGIBLE', '820', '10204'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020405', 'NEGATIVE', '(-) DETERIORO ACUMULADO DE ACTIVO INTANGIBLE', '(-) DETERIORO ACUMULADO DE ACTIVO INTANGIBLE', '830', '10204'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020406', 'POSITIVE', 'OTROS INTANGIBLES', 'OTROS INTANGIBLES', '840', '10204'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10205', 'POSITIVE', 'ACTIVOS POR IMPUESTOS DIFERIDOS', 'ACTIVOS POR IMPUESTOS DIFERIDOS', '850', '102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10206', 'DUAL', 'ACTIVOS FINANCIEROS NO CORRIENTES', 'ACTIVOS FINANCIEROS NO CORRIENTES', '870', '102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020601', 'POSITIVE', 'ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO', 'ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO', '880', '10206'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020602', 'NEGATIVE', '(-) PROVISION POR DETERIORO DE ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO', '(-) PROVISION POR DETERIORO DE ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO', '890', '10206'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020603', 'POSITIVE', 'DOCUMENTOS Y CUENTAS POR COBRAR', 'DOCUMENTOS Y CUENTAS POR COBRAR', '900', '10206'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020604', 'NEGATIVE', '(-) PROVISIÓN CUENTAS INCOBRABLES DE ACTIVOS FINANCIEROS NO CORRIENTES', '(-) PROVISIÓN CUENTAS INCOBRABLES DE ACTIVOS FINANCIEROS NO CORRIENTES', '910', '10206'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','10207', 'DUAL', 'OTROS ACTIVOS NO CORRIENTES', 'OTROS ACTIVOS NO CORRIENTES', '920', '102'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020701', 'POSITIVE', 'INVERSIONES SUBSIDIARIAS', 'INVERSIONES SUBSIDIARIAS', '930', '10207'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020702', 'POSITIVE', 'INVERSIONES ASOCIADAS', 'INVERSIONES ASOCIADAS', '940', '10207'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020703', 'POSITIVE', 'INVERSIONES NEGOCIOS CONJUNTOS', 'INVERSIONES NEGOCIOS CONJUNTOS', '950', '10207'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020704', 'POSITIVE', 'OTRAS INVERSIONES', 'OTRAS INVERSIONES', '960', '10207'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020705', 'NEGATIVE', '(-) PROVISIÓN VALUACIÓN DE INVERSIONES', '(-) PROVISIÓN VALUACIÓN DE INVERSIONES', '970', '10207'); 
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('ASSETS','1020706', 'POSITIVE', 'OTROS ACTIVOS NO CORRIENTES', 'OTROS ACTIVOS NO CORRIENTES', '980', '10207'); 

 
 INSERT INTO `rest_services_db`.`account` (`id`, `account_type`, `account_value_type`, `description`, `name`, `order_weight`) VALUES ('2', 'LIABILITIES', 'DUAL', 'PASIVO', 'PASIVO', '990');
 INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','201', 'DUAL', 'PASIVO CORRIENTE', 'PASIVO CORRIENTE', '1000', '2');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20101', 'POSITIVE', 'PASIVOS FINANCIEROS A VALOR RAZONABLE CON CAMBIOS EN RESULTADOS', 'PASIVOS FINANCIEROS A VALOR RAZONABLE CON CAMBIOS EN RESULTADOS', '1010', '201');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20102', 'POSITIVE', 'PASIVOS POR CONTRATOS DE ARRENDAMIENTO FINANCIEROS', 'PASIVOS POR CONTRATOS DE ARRENDAMIENTO FINANCIEROS', '1020', '201');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20103', 'DUAL', 'CUENTAS Y DOCUMENTOS POR PAGAR', 'CUENTAS Y DOCUMENTOS POR PAGAR', '1030', '201');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2010301', 'POSITIVE', 'LOCALES', 'LOCALES', '1040', '20103');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2010302', 'POSITIVE', 'DEL EXTERIOR', 'DEL EXTERIOR', '1050', '20103');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20104', 'DUAL', 'OBLIGACIONES CON INSTITUCIONES FINANCIERAS', 'OBLIGACIONES CON INSTITUCIONES FINANCIERAS', '1060', '201');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2010401', 'POSITIVE', 'LOCALES', 'LOCALES', '1070', '20104');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2010402', 'POSITIVE', 'DEL EXTERIOR', 'DEL EXTERIOR', '1090', '20104');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20105', 'DUAL', 'PROVISIONES', 'PROVISIONES', '1100', '201');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2010501', 'POSITIVE', 'LOCALES', 'LOCALES', '1110', '20105');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2010502', 'POSITIVE', 'DEL EXTERIOR', 'DEL EXTERIOR', '1120', '20105');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20106', 'POSITIVE', 'PORCIÓN CORRIENTE DE OBLIGACIONES EMITIDAS', 'PORCIÓN CORRIENTE DE OBLIGACIONES EMITIDAS', '1130', '201');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20107', 'DUAL', 'OTRAS OBLIGACIONES CORRIENTES', 'OTRAS OBLIGACIONES CORRIENTES', '1140', '201');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2010701', 'POSITIVE', 'CON LA ADMINISTRACIÓN TRIBUTARIA', 'CON LA ADMINISTRACIÓN TRIBUTARIA', '1150', '20107');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2010702', 'POSITIVE', 'IMPUESTO A LA RENTA POR PAGAR DEL EJERCICIO', 'IMPUESTO A LA RENTA POR PAGAR DEL EJERCICIO', '1160', '20107');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2010703', 'POSITIVE', 'CON EL IESS', 'CON EL IESS', '1170', '20107');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2010704', 'POSITIVE', 'POR BENEFICIOS DE LEY A EMPLEADOS', 'POR BENEFICIOS DE LEY A EMPLEADOS', '1180', '20107');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2010705', 'POSITIVE', 'PARTICIPACIÓN TRABAJADORES POR PAGAR DEL EJERCICIO', 'PARTICIPACIÓN TRABAJADORES POR PAGAR DEL EJERCICIO', '1190', '20107');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2010706', 'POSITIVE', 'DIVIDENDOS POR PAGAR', 'DIVIDENDOS POR PAGAR', '1200', '20107');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20108', 'POSITIVE', 'CUENTAS POR PAGAR DIVERSAS/RELACIONADAS', 'CUENTAS POR PAGAR DIVERSAS/RELACIONADAS', '1210', '201');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20109', 'POSITIVE', 'OTROS PASIVOS FINANCIEROS', 'OTROS PASIVOS FINANCIEROS', '1220', '201');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20110', 'POSITIVE', 'ANTICIPOS DE CLIENTES', 'ANTICIPOS DE CLIENTES', '1230', '201');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20111', 'POSITIVE', 'PASIVOS DIRECTAMENTE ASOCIADOS CON LOS ACTIVOS NO CORRIENTES Y OPERACIONES DISCONTINUADAS', 'PASIVOS DIRECTAMENTE ASOCIADOS CON LOS ACTIVOS NO CORRIENTES Y OPERACIONES DISCONTINUADAS', '1240', '201');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20112', 'DUAL', 'PORCION CORRIENTE DE PROVISIONES POR BENEFICIOS A EMPLEADOS', 'PORCION CORRIENTE DE PROVISIONES POR BENEFICIOS A EMPLEADOS', '1250', '201');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2011201', 'POSITIVE', 'JUBILACION PATRONAL', 'JUBILACION PATRONAL', '1260', '20112');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2011202', 'POSITIVE', 'OTROS BENEFICIOS A LARGO PLAZO PARA LOS EMPLEADOS', 'OTROS BENEFICIOS A LARGO PLAZO PARA LOS EMPLEADOS', '1270', '20112');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20113', 'POSITIVE', 'OTROS PASIVOS CORRIENTES', 'OTROS PASIVOS CORRIENTES', '1280', '201');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','202', 'DUAL', 'PASIVO NO CORRIENTE', 'PASIVO NO CORRIENTE', '1300', '2');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20201', 'POSITIVE', 'PASIVOS POR CONTRATOS DE ARRENDAMIENTO FINANCIERO', 'PASIVOS POR CONTRATOS DE ARRENDAMIENTO FINANCIERO', '1320', '202');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20202', 'DUAL', 'CUENTAS Y DOCUMENTOS POR PAGAR', 'CUENTAS Y DOCUMENTOS POR PAGAR', '1330', '202');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2020201', 'POSITIVE', 'LOCALES', 'LOCALES', '1340', '20202');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2020202', 'POSITIVE', 'DEL EXTERIOR', 'DEL EXTERIOR', '1350', '20202');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20203', 'DUAL', 'OBLIGACIONES CON INSTITUCIONES FINANCIERAS', 'OBLIGACIONES CON INSTITUCIONES FINANCIERAS', '1360', '202');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2020301', 'POSITIVE', 'LOCALES', 'LOCALES', '1370', '20203');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2020302', 'POSITIVE', 'DEL EXTERIOR', 'DEL EXTERIOR', '1380', '20203');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20204', 'DUAL', 'CUENTAS POR PAGAR DIVERSAS/RELACIONADAS', 'CUENTAS POR PAGAR DIVERSAS/RELACIONADAS', '1390', '202');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2020401', 'POSITIVE', 'LOCALES', 'LOCALES', '1400', '20204');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2020402', 'POSITIVE', 'DEL EXTERIOR', 'DEL EXTERIOR', '1410', '20204');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20205', 'POSITIVE', 'OBLIGACIONES EMITIDAS', 'OBLIGACIONES EMITIDAS', '1420', '202');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20206', 'POSITIVE', 'ANTICIPOS DE CLIENTES', 'ANTICIPOS DE CLIENTES', '1430', '202');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20207', 'DUAL', 'PROVISIONES POR BENEFICIOS A EMPLEADOS', 'PROVISIONES POR BENEFICIOS A EMPLEADOS', '1440', '202');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2020701', 'POSITIVE', 'JUBILACION PATRONAL', 'JUBILACION PATRONAL', '1450', '20207');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2020702', 'POSITIVE', 'OTROS BENEFICIOS NO CORRIENTES PARA LOS EMPLEADOS', 'OTROS BENEFICIOS NO CORRIENTES PARA LOS EMPLEADOS', '1460', '20207');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20208', 'POSITIVE', 'OTRAS PROVISIONES', 'OTRAS PROVISIONES', '1470', '202');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20209', 'DUAL', 'PASIVO DIFERIDO', 'PASIVO DIFERIDO', '1480', '202');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2020901', 'POSITIVE', 'INGRESOS DIFERIDOS', 'INGRESOS DIFERIDOS', '1490', '20209');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','2020902', 'POSITIVE', 'PASIVOS POR IMPUESTOS DIFERIDOS', 'PASIVOS POR IMPUESTOS DIFERIDOS', '1500', '20209');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('LIABILITIES','20210', 'POSITIVE', 'OTROS PASIVOS NO CORRIENTES', 'OTROS PASIVOS NO CORRIENTES', '1510', '202');

INSERT INTO `rest_services_db`.`account` (`id`, `account_type`, `account_value_type`, `description`, `name`, `order_weight`) VALUES ('3', 'EQUITY', 'DUAL', 'PATRIMONIO NETO', 'PATRIMONIO NETO', '1520');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30', 'DUAL', 'PATRIMONIO ATRIBUIBLE A LOS PROPIETARIOS DE LA CONTROLADORA', 'PATRIMONIO ATRIBUIBLE A LOS PROPIETARIOS DE LA CONTROLADORA', '1560', '3');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','301', 'DUAL', 'CAPITAL', 'CAPITAL', '1570', '30');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30101', 'POSITIVE', 'CAPITAL SUSCRITO o ASIGNADO', 'CAPITAL SUSCRITO o ASIGNADO', '1580', '301');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30102', 'NEGATIVE', '(-) CAPITAL SUSCRITO NO PAGADO, ACCIONES EN TESORERÍA', '(-) CAPITAL SUSCRITO NO PAGADO, ACCIONES EN TESORERÍA', '1590', '301');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','302', 'POSITIVE', 'APORTES DE SOCIOS O ACCIONISTAS PARA FUTURA CAPITALIZACIÓN', 'APORTES DE SOCIOS O ACCIONISTAS PARA FUTURA CAPITALIZACIÓN', '1600', '30');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','303', 'POSITIVE', 'PRIMA POR EMISIÓN PRIMARIA DE ACCIONES', 'PRIMA POR EMISIÓN PRIMARIA DE ACCIONES', '1610', '30');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','304', 'DUAL', 'RESERVAS', 'RESERVAS', '1620', '30');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30401', 'POSITIVE', 'RESERVA LEGAL', 'RESERVA LEGAL', '1630', '304');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30402', 'POSITIVE', 'RESERVAS FACULTATIVA Y ESTATUTARIA', 'RESERVAS FACULTATIVA Y ESTATUTARIA', '1640', '304');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','305', 'DUAL', 'OTROS RESULTADOS INTEGRALES', 'OTROS RESULTADOS INTEGRALES', '1650', '30');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30501', 'POSITIVE', 'SUPERAVIT DE ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA', 'SUPERAVIT DE ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA', '1660', '305');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30502', 'POSITIVE', 'SUPERAVIT POR REVALUACIÓN DE PROPIEDADES, PLANTA Y EQUIPO', 'SUPERAVIT POR REVALUACIÓN DE PROPIEDADES, PLANTA Y EQUIPO', '1670', '305');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30503', 'POSITIVE', 'SUPERAVIT POR REVALUACION DE ACTIVOS INTANGIBLES', 'SUPERAVIT POR REVALUACION DE ACTIVOS INTANGIBLES', '1680', '305');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30504', 'POSITIVE', 'OTROS SUPERAVIT POR REVALUACION', 'OTROS SUPERAVIT POR REVALUACION', '1690', '305');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','306', 'DUAL', 'RESULTADOS ACUMULADOS', 'RESULTADOS ACUMULADOS', '1700', '30');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30601', 'POSITIVE', 'GANANCIAS ACUMULADAS', 'GANANCIAS ACUMULADAS', '1710', '306');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30602', 'NEGATIVE', '(-) PÉRDIDAS ACUMULADAS', '(-) PÉRDIDAS ACUMULADAS', '1720', '306');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30603', 'DUAL', 'RESULTADOS ACUMULADOS PROVENIENTES DE LA ADOPCION POR PRIMERA VEZ DE LAS NIIF', 'RESULTADOS ACUMULADOS PROVENIENTES DE LA ADOPCION POR PRIMERA VEZ DE LAS NIIF', '1730', '306');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30604', 'DUAL', 'RESERVA DE CAPITAL', 'RESERVA DE CAPITAL', '1740', '306');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30605', 'POSITIVE', 'RESERVA POR DONACIONES', 'RESERVA POR DONACIONES', '1750', '306');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30606', 'DUAL', 'RESERVA POR VALUACIÓN', 'RESERVA POR VALUACIÓN', '1760', '306');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30607', 'DUAL', 'SUPERÁVIT POR REVALUACIÓN DE INVERSIONES', 'SUPERÁVIT POR REVALUACIÓN DE INVERSIONES', '1770', '306');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','307', 'DUAL', 'RESULTADOS DEL EJERCICIO', 'RESULTADOS DEL EJERCICIO', '1780', '3');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30701', 'POSITIVE', 'GANANCIA NETA DEL PERIODO', 'GANANCIA NETA DEL PERIODO', '1790', '307');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','30702', 'NEGATIVE', '(-) PÉRDIDA NETA DEL PERIODO', '(-) PÉRDIDA NETA DEL PERIODO', '1800', '307');
INSERT INTO `rest_services_db`.`account` (`account_type`, `id`, `account_value_type`, `description`, `name`, `order_weight`, `parent_account_id`) VALUES('EQUITY','31', 'POSITIVE', 'PARTICIPACION NO CONTROLADORAS', 'PARTICIPACION NO CONTROLADORAS', '1820', '3');